INCFLAGS :=
LIBRETRO_COMM_DIR := $(CORE_DIR)/libretro-common

ifneq (,$(findstring msvc2003,$(platform)))
INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include/compat/msvc
endif

INCFLAGS += -I$(LIBRETRO_COMM_DIR)/include

SOURCES_C := \
	$(CORE_DIR)/libretro.c \
	$(CORE_DIR)/plateform.c \
	$(wildcard $(CORE_DIR)/libmad/*.c) \
	$(wildcard $(CORE_DIR)/zip/*.c) \
	$(wildcard $(CORE_DIR)/zip/zlib/*.c)
